package com.cafeteria.cafeteria_client.data;

import java.util.ArrayList;

/**
 * Created by Shira Elitzur on 08/09/2016.
 * This class represent a food category in the cafeteria menu.
 */
public class Category {

    private String description;
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDescription() {
        return description;
    }
    /**
     * The id of this category (auto generated by db)
     */
    private int id;

    /**
     * The title of this category
     */
    private String title;

    /**
     * The items of this category
     */
    private ArrayList<Item> items;

    /**
     * The meals of this category
     */
    private ArrayList<Meal> meals;

    /**
     * The constructor of Category object sets its title as the given parameter
     * @param title
     */
    public Category( String title ) {
        this.setTitle(title);
    }

    /**
     * Constructor without parameters - a must in JPA Entity
     */
    public Category() {

    }

    /**
     * Returns the id of this category
     * @return the id of this category
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this category
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of this category
     * @return the title of this category
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets title for this category
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the items of this category
     * @return the items of this category
     */
    public ArrayList<Item> getItems() {
        return items;
    }

    /**
     * Sets items list to this category
     * @param items
     */
    public void setItems(ArrayList<Item> items) {
        this.items = items;
    }

    /**
     * Returns the meals of this category
     * @return
     */
    public ArrayList<Meal> getMeals() {
        return meals;
    }

    /**
     * Sets meals list to this category
     * @param meals
     */
    public void setMeals(ArrayList<Meal> meals) {
        this.meals = meals;
    }

}
