package com.cafeteria.cafeteria_client.data;

import com.cafeteria.cafeteria_client.OrderItem;

import java.io.Serializable;

/**
 *
 * @author Shira Elitzur
 *
 * An instance of this class represent A single item from the cafeteria menu
 *
 */
public class Item implements Serializable,OrderItem {

    /**
     * The id of this item (auto generated by db)
     */
    private int id;

    /**
     * The title of this item.
     * 1-3 words that describes the item
     */
    private String title;

    /**
     * An indication if this item is for sale as is or only as part of a meal
     */
    private boolean isStandAlone;

    /**
     * The price of this item (only for stand alone item)
     */
    private double price;

    /**
     * The category of this item (food category like drinks, salads...)
     */
    private Category category;


    /**
     * Returns the id of this item
     * @return the id of this item
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this item
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of this item
     * @return the title of this item
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets title to this item
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Retruns true if this item is for sale as is or false if it is only part of a meal
     * @return true if this item is for sale as is
     */
    public boolean isStandAlone() {
        return isStandAlone;
    }

    /**
     * Sets if this item is for sale as is or only as part of a meal
     * @param isStandAlone
     */
    public void setStandAlone(boolean isStandAlone) {
        this.isStandAlone = isStandAlone;
    }

    /**
     * Returns the price of this item
     * @return
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets price for this item
     * @param price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Returns the category of this item
     * @return the category of this item
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets category object for this item
     * @param category
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", isStandAlone=" + isStandAlone +
                ", price=" + price +
                ", category=" + category +
                '}';
    }
}
