package com.cafeteria.cafeteria_client.data;

import com.cafeteria.cafeteria_client.interfaces.OrderItem;

import java.util.List;


/**
 *
 * @author Shira Elitzur
 *
 * An instance of this class represent A specific meal that a specific customer ordered.
 * An ordered meal will contain a list of the chosen extras and it can contain a comment
 *
 */
public class OrderedMeal implements OrderItem {

    /**
     * The id of this ordered meal (auto generated by db)
     */
    private int id;

    /**
     * The meal in the menu that this ordered meal is an actual instance of
     */
    private Meal parentMeal;

    /**
     * List of the extras that the customer chose
     */
    private List<Item> chosenExtras;

    /**
     * The drink that the customer chose (optional)
     */
    private Drink chosenDrink;

    /**
     * The customer can attach comment to the ordered meal
     */
    private String comment;

    /**
     * The parent-order of this ordered meal
     */
    private Order order;



    /**
     * Returns the id of this ordered meal
     * @return the id of this ordered meal
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this ordered meal
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the Meal that is this orderer-meal parent
     * @return
     */
    public Meal getParentMeal() {
        return parentMeal;
    }

    /**
     * Sets meal as parent meal for this ordered meal
     * @param parentMeal
     */
    public void setParentMeal(Meal parentMeal) {
        this.parentMeal = parentMeal;
    }

    /**
     * Returns the list of the extras that the customer chose for his meal ( this meal...)
     * @return the list of the extras that the customer chose
     */
    public List<Item> getChosenExtras() {
        return chosenExtras;
    }

    /**
     * Sets the list of extras that the customer chose
     * @param chosenExtras
     */
    public void setChosenExtras(List<Item> chosenExtras) {
        this.chosenExtras = chosenExtras;
    }

    /**
     * Returns the Drink that the customer chose
     * @return the Drink that the customer chose
     */
    public Drink getChosenDrink() {
        return chosenDrink;
    }

    /**
     * Sets drink (the customer choice) to this meal
     * @param chosenDrink
     */
    public void setChosenDrink(Drink chosenDrink) {
        this.chosenDrink = chosenDrink;
    }

    /**
     * Returns the comment that the customer attached to the meal
     * @return comment that was attached to the meal
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets a comment to the ordered meal ( customer comment. example:
     * "must be ready until 14:00")
     * @param comment
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Returns the order object of this ordered meal
     * @return the order object of the meal
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets order object to this meal
     * @param order
     */
    public void setOrder(Order order) {
        this.order = order;
    }

    /**
     *  This method must be override here because the class implements OrderItem Interface
     * @return
     */
    @Override
    public String getTitle() {
        return getParentMeal().getTitle();
    }

    @Override
    public double getPrice() {
        return getParentMeal().getPrice();
    }

    @Override
    public String toString() {
        return "OrderedMeal{" +
                "id=" + id +
                ", parentMeal=" + parentMeal +
                ", chosenExtras=" + chosenExtras +
                ", chosenDrink=" + chosenDrink +
                ", comment='" + comment + '\'' +
                ", order=" + order +
                '}';
    }
}
