package com.cafeteria.cafeteria_client.data;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;


/**
 *
 * @author Shira Elitzur
 *
 * An instance of this class represent an order from the cafeteria
 */
public class Order {

    /**
     * The id of the order (auto generated by db)
     */
    private int id;

    /**
     * The customer who made this order
     */
    private Customer customer;

    /**
     * The meals that this order contains
     */
    private List<OrderedMeal> meals;

    /**
     * The items that this order contains
     */
    private List<Item> items;

    /**
     * The date and time when this order created
     */
    private Calendar calendar;

    /**
     * The amount to pay for the items/meals in this order
     */
    private double payment;

    /**
     * An indicator if the customer already paid for this order
     */
    private boolean isPaid;

    /**
     * An indicator if the order was delivered
     */
    private boolean isDelivered;

    /**
     * An indicator if the order is ready
     */
    private boolean isReady;

    /**
     * The customer can attach a comment to his order
     */
    private String comment;



    /**
     * Returns the id of this order
     * @return the id of this order
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id for this order
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the customer that made this order
     * @return the customer that made this order
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets customer object to this order
     * @param customer
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Returns the meals that this order contains
     * @return the meals that this order contains
     */
    public List<OrderedMeal> getMeals() {
        return meals;
    }

    /**
     * Sets list of meals for this order
     * @param meals
     */
    public void setMeals(List<OrderedMeal> meals) {
        this.meals = meals;
    }

    /**
     * Returns the items that this order contains
     * @return the items that this order contains
     */
    public List<Item> getItems() {
        return items;
    }

    /**
     * Sets list of items for this order
     * @param items
     */
    public void setItems(List<Item> items) {
        this.items = items;
    }

    /**
     * Returns the Date&Time when this order was created
     * @return
     */
    public Calendar getCalendar() {
        return calendar;
    }

    /**
     * Sets the Date and Time for this order ( when it was created )
     * @param
     */
    public void setCalendar(Calendar calendar) {
        this.calendar = calendar;
    }

    /**
     * Returns the amount to pay for this order
     * @return the amount to pay for this order
     */
    public double getPayment() {
        payment = 0;
        for( OrderedMeal meal : getMeals() ) {
            payment += meal.getParentMeal().getPrice();
        }

        for( Item item : getItems() ) {
            payment += item.getPrice();
        }

        return payment;
    }

    /**
     * Sets the amount to pay for this order
     * @param payment
     */
    public void setPayment(double payment) {
        this.payment = payment;
    }

    /**
     * Returns true if the order was already paid or false if not
     * @return true if the order was already paid
     */
    public boolean isPaid() {
        return isPaid;
    }

    /**
     * Sets true if the order was already paid or false if not
     * @param isPaid
     */
    public void setPaid(boolean isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * Returns true if the order was already delivered or false if not
     * @return true if the order was already delivered
     */
    public boolean isDelivered() {
        return isDelivered;
    }

    /**
     * Sets whether order was already delivered or false if not
     * @param isDelivered
     */
    public void setDelivered(boolean isDelivered) {
        this.isDelivered = isDelivered;
    }

    /**
     * Returns true if the order is ready or false if it is not yet ready
     * @return
     */
    public boolean isReady() {
        return isReady;
    }

    /**
     * Sets whether the order is ready
     * @param isReady
     */
    public void setReady(boolean isReady) {
        this.isReady = isReady;
    }

    /**
     * Returns the comment that was attached to this order
     * @return the comment of this order
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets comment to this order
     * @param comment
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}
