package com.cafeteria.cafeteria_client.data;

import java.io.Serializable;

/**
 * Created by anael on 07/12/16.
 */

public class Server implements Serializable{

    /**
     * The id of the order (auto generated by db)
     */
    private int id;

    private String cafeteriaName;

    private String address;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCafeteriaName() {
        return cafeteriaName;
    }

    public void setCafeteriaName(String cafeteriaName) {
        this.cafeteriaName = cafeteriaName;
    }
}

